defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

wandb:
  project: "cifar10_model_compression"
  entity: "vitoryeso"
  tags: ["compression", "pruning", "quantization"]

training:
  epochs: 100
  early_stopping_patience: 10
  early_stopping_min_delta: 0.001
  models_path: "models/"
  data_path: "data/"

optimization:
  lr: 0.075
  momentum: 0.9
  batch_size: 256

compression:
  gamma: 0.5  # pruning threshold
  bits: 8     # quantization bits

# Define sweeps
hydra:
  sweeper:
    params:
      optimization.lr: 0.001,0.01,0.075
      optimization.batch_size: 64,128,256
      compression.gamma: 0.25,0.5,0.75
      compression.bits: 4,8,16 